# These are supported funding model platforms

github : Dgh1351 
patreon:  Dgh1351 
open_collective: Dgh1351 
ko_fi: Dgh1351 
tidelift: Dgh1351 
community_bridge: Dgh1351 
liberapay: Dgh1351 
issuehunt: Dgh1351 
otechie: Dgh1351 
lfx_crowdfunding: Dgh1351 
custom: Dgh1351 
